version: "3.9"
services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
          - .:/app
    depends_on:
      - database
      
  
  database:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
  
