# Generated by Django 4.2.6 on 2023-10-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0002_noticeinvestment_noticeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='reward',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticeproduct',
            name='notice_duration',
            field=models.DurationField(help_text='The duration you need to wait after giving a notice'),
        ),
    ]
