# Generated by Django 4.2.6 on 2023-10-07 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0003_alter_investment_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
