# Generated by Django 4.2.6 on 2023-10-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0004_alter_investment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
