# Generated by Django 4.2.6 on 2023-10-07 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0005_investmentproduct_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentproduct',
            name='is_active',
        ),
    ]
