# Generated by Django 4.2.6 on 2023-10-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quests', '0003_quest_investments_unlocks_quest_order'),
        ('MyUsers', '0003_alter_childuser_options_alter_parentuser_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childuser',
            name='completed_quests',
            field=models.ManyToManyField(blank=True, related_name='completed_quests', to='Quests.quest'),
        ),
    ]
