# Generated by Django 4.2.6 on 2023-10-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUsers', '0004_childuser_completed_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='childuser',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
    ]
