# Generated by Django 4.2.6 on 2023-10-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUsers', '0005_childuser_is_parent_parentuser_is_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childuser',
            name='is_parent',
        ),
        migrations.RemoveField(
            model_name='parentuser',
            name='is_parent',
        ),
        migrations.AddField(
            model_name='user',
            name='is_parent',
            field=models.BooleanField(default=True),
        ),
    ]
