# Generated by Django 4.2.6 on 2023-10-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quests', '0009_alter_questcategory_options'),
        ('MyUsers', '0006_remove_childuser_is_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childuser',
            name='completed_categories',
            field=models.ManyToManyField(blank=True, related_name='completed_categories', to='Quests.questcategory'),
        ),
    ]
