# Generated by Django 4.2.6 on 2023-10-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyUsers', '0007_childuser_completed_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childuser',
            name='completed_categories',
        ),
    ]
