# Generated by Django 4.2.6 on 2023-10-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyUsers', '0007_user_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
