# Generated by Django 4.2.6 on 2023-10-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('target_balance', models.FloatField()),
                ('achieved', models.BooleanField(default=False)),
            ],
        ),
    ]
