# Generated by Django 4.2.6 on 2023-10-06 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyUsers', '0003_alter_childuser_options_alter_parentuser_options_and_more'),
        ('Goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_goals', to='MyUsers.childuser'),
        ),
    ]
