# Generated by Django 4.2.6 on 2023-10-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0002_goals_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='reward',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='goals',
            name='target_balance',
            field=models.FloatField(default=0),
        ),
    ]
