# Generated by Django 4.2.6 on 2023-10-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goals', '0003_goals_reward_alter_goals_target_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='current_balance',
            field=models.FloatField(default=0),
        ),
    ]
