# Generated by Django 4.2.6 on 2023-10-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='reward',
            field=models.FloatField(default=0),
        ),
    ]
