# Generated by Django 4.2.6 on 2023-10-07 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quests', '0003_quest_investments_unlocks_quest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quest',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='questcategory',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
