# Generated by Django 4.2.6 on 2023-10-07 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0004_alter_investment_start_date'),
        ('Quests', '0003_quest_investments_unlocks_quest_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='investments_unlocks',
        ),
        migrations.AddField(
            model_name='questcategory',
            name='investment_unlocks',
            field=models.ManyToManyField(blank=True, to='Investments.investmentproduct'),
        ),
    ]
