# Generated by Django 4.2.6 on 2023-10-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quests', '0004_remove_quest_investments_unlocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questcategory',
            name='category_completed',
            field=models.BooleanField(default=False),
        ),
    ]
