# Generated by Django 4.2.6 on 2023-10-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quests', '0005_questcategory_category_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
