# Generated by Django 4.2.6 on 2023-10-07 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quests', '0007_remove_quest_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questcategory',
            name='category_completed',
        ),
    ]
