# Generated by Django 4.2.6 on 2023-10-07 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quests', '0008_remove_questcategory_category_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questcategory',
            options={'verbose_name_plural': 'Quest Categories'},
        ),
    ]
