# Generated by Django 4.2.6 on 2023-10-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Investments', '0005_investmentproduct_is_active'),
        ('Quests', '0009_alter_questcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='investments_unlocks',
            field=models.ManyToManyField(blank=True, to='Investments.investmentproduct'),
        ),
    ]
