# Generated by Django 4.2.6 on 2023-10-07 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quests', '0010_quest_investments_unlocks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'verbose_name_plural': 'Quests'},
        ),
    ]
