# Generated by Django 4.2.6 on 2023-10-07 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quests', '0011_alter_quest_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questcategory',
            name='investment_unlocks',
        ),
    ]
